### ISSUE TITLE
Missing-argument help-message has duplicate names

### ISSUE THREAD

**Issue by akhanf** [akhanf/snakebids#105]
Just made one argument in hippunfold a required one, e.g. snakebids.yml excerpt here:

```
  --modality:
    help: 'Type of image to run hippunfold on. Modality prefixed with seg will import an existing (manual) hippocampal tissue segmentation from that space, instead of running neural network (default: %(default)s)'
    required: True
    choices:
      - T1w
      - T2w
      - hippb500
      - segT1w
      - segT2w
      - cropseg
```

but when a user doesn't provide the required arg we get the following error message:

```
hippunfold: error: the following arguments are required: --modality/--modality/--modality
```
The problem here is --modality is repeated three times identically.. 

Pretty minor problem, since it's just in the help output, but something to make note of regardless. I am guessing the code that is adding hyphen alternatives might be doing this, but haven't checked it out.
