### ISSUE TITLE
How to deal with missing session data

### ISSUE THREAD

**Issue by ljhearne** [akhanf/snakebids#230]
## The problem

I have a dataset where some subjects have not completed all the sessions, e.g.,

```
sub-01
- ses-A
- ses-B
sub-02
-ses-A
sub-03
- ses-A
- ses-B
```

Using snakebids tools the workflow will fail trying to look for sub-02 ses-B.

```
pybids_inputs:
  bold:
    filters:
      suffix: 'bold'
      desc: 'preproc'
      extension: 'nii.gz'
      space: 'MNI152NLin2009cAsym'
      datatype: 'func'
      task: 'rest'
      res: '2'
    wildcards:
     - subject
     - session
```
and 
```
inputs = generate_inputs(
    bids_dir=config['fmriprep_dir'],
    pybids_inputs=config['pybids_inputs'],
    use_bids_inputs=True)
```

The inputs BidsDataset correctly identifies the subject and session pairs, which can be printed with:
```
for subj, ses in zip(inputs['bold'].zip_lists['subject'], inputs['bold'].zip_lists['session']):
    print(subj, ses)
```
But these subj-session pairings don't propagate in snakemake. I suppose it just takes all the possible subject wildcards and session wildcards.
